version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directory: "/member-portal-backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/member-portal-frontend"
    schedule:
      interval: "weekly"