name: deploy docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          pip install mkdocs-material

      - name: copy swagger
        run: |
          cp -r -f ./swagger ./docs/docs/swagger

      - run: mkdocs gh-deploy --config-file ./docs/mkdocs.yml