name: deploy docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: lock package version
        run: pipenv lock

      - name: install packages
        run: pipenv sync --dev

      - name: copy swagger
        run: |
          cp -r -f ./swagger ./docs/docs/swagger

      - run: pipenv shell mkdocs gh-deploy --force --config-file ./docs/mkdocs.yml