name: Check pull request

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'member-portal-frontend/**'

defaults:
  run:
    working-directory: member-portal-frontend

permissions:
  statuses: write

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: member-portal-frontend